# loyalty-app tests (the PWA app)

name: loyalty-app (PWA) tests

on:
  pull_request:
    paths:
      - 'loyalty-app/**'
  push:
    paths:
      - 'loyalty-app/**'

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - name: Setup Node.js
        uses: actions/setup-node@v1
        with:
          node-version: 12
      - name: Install
        run: yarn install
        working-directory: loyalty-app
      - name: Test
        run: yarn test
        working-directory: loyalty-app
