name: loyalty-panel s3-deploy

on:
  push:
    paths:
      - 'loyalty-panel/**'
    branches:
      - master

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - name: Configure AWS Credentials
        uses: aws-actions/configure-aws-credentials@v1
        with:
          aws-access-key-id: ${{ secrets.AWS_ACCESS_KEY_ID }}
          aws-secret-access-key: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
          aws-region: ${{ secrets.AWS_REGION }}
      - name: Authenticate with GitHub package registry
        run: echo "//npm.pkg.github.com/:_authToken=${{ secrets.READ_ORG_PACKAGES }}" > ~/.npmrc
      - name: Install and build
        run: npm install && npm run build
        working-directory: loyalty-panel
      - name: Deploy to S3 bucket
        run: aws s3 sync ./build s3://panel-getloyaltyapp --delete
        working-directory: loyalty-panel
